config/routes.rb
BandungBangkitBersinar::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => :user_registrations}

  resources :transactions

  resources :mix_items

  resources :users, { path:"user-management" } do
    collection do
      delete :delete_all
    end
    get :export
  end

  resources :suppliers do
    collection do
      delete :delete_all
      get :print_preview
      get :items_info
      get :export
    end
    get :print_orders, :on => :member
  end

  resources :customers do
    collection do
      delete :delete_all
      get :export
      get :items_info
    end
  end

  resources :categories do
    collection do
      delete :delete_all
      get :export
    end
  end

  resources :items do
    collection do
      delete :delete_all
      get :critical
      get :export
    end
  end

  resources :purchase_orders, except: [:edit, :update, :destroy] do
    collection do
      get :supplier_info
      get :items_info
      get :export
    end
    get :print_po, :on => :member
  end

  resources :sales_invoices, except: [:edit, :update, :destroy] do
    collection do
      get :customer_info
      get :items_info
      get :export
    end
    get :print_invoice, :on => :member
  end

  resources :companies, only: [:edit, :update]

  resources :receive_orders, except: [:edit, :update, :destroy] do
    get :export, :on => :collection
    get :print_invoice, :on => :member
  end

  resources :manage_stocks, :except => [:new, :show, :destroy]

  resources :reports, only: [:index, :create] do
    collection do
      get :preview
    end
  end

  resources :supplier_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end

  resources :customer_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end
  resources :rek_accounts, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end


  get "po_history" => "home#purchase_history", :as => "po_history"
  get "sales_history" => "home#sales_history", :as => "sales_history"
  get "file_managers"=>"home#file_managers", :as => "file_managers"
  get "return_po_number/:date" => "purchase_orders#return_number", :as => "return_po_number"
  get "return_so_number/:date" => "sales_invoices#return_number", :as => "return_so_number"
  get "return_receive_number/:date" => "receive_orders#return_number", :as => "return_receive_number"
  get "return_supplier_payment_number/:date" => "supplier_payments#return_number", :as => "return_supplier_payment_number"
  get "return_customer_payment_number/:date" => "customer_payments#return_number", :as => "return_customer_payment_number"
  get "manage_stock/:invoice_number/item/:item_id" => "manage_stocks#new", :as => "manage_item_stock"
  get "reset_data" => "home#reset_data", as: "reset_data"

  root :to => 'home#index'

  match 'elfinder' => 'home#elfinder'
  match '*path', :to => 'pages#routing_error'
end

app/views/shared/_left_menu.html.erb
<!-- left menu starts -->
<div class="span2 main-menu-span">
  <div class="well nav-collapse sidebar-nav">
    <ul class="nav nav-tabs nav-stacked main-menu">
      <li class="nav-header hidden-tablet">Main</li>
      <li>
        <%= link_to root_path do %>
          <i class="icon-home"></i>
          <span class="hidden-tablet"> Dashboard</span>
        <% end %>
      </li>
      <li class="nav-header hidden-tablet">Data Master</li>
      <% if can?(:manage, User) %>
        <li>
          <%= link_to users_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Users</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, Supplier) %>
        <li>
          <%= link_to suppliers_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Suppliers</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, Item) %>
        <li>
          <%= link_to items_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Items</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, MixItem) %>
        <li>
          <%= link_to mix_items_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Mix Items</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, Customer) %>
        <li>
          <%= link_to customers_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Customers</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, Category) %>
        <li>
          <%= link_to categories_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Categories</span>
          <% end %>
        </li>
      <% end %>
      <li class="nav-header hidden-tablet">Transaksi</li>
      <% if can?(:manage, PurchaseOrder) %>
        <li>
          <%= link_to purchase_orders_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Purchase Orders</span>
          <% end %>
        </li>
        <li>
          <%= link_to receive_orders_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Receive Orders</span>
          <% end %>
        </li>
        <li>
          <%= link_to manage_stocks_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Manage Stock</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, SalesInvoice) %>
        <li>
          <%= link_to sales_invoices_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Sales Orders</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, SupplierPayment) %>
        <li class="nav-header hidden-tablet">Payment</li>
        <% if can?(:manage, SupplierPayment) || can?(:manage, CustomerPayment)%>
          <li>
            <%= link_to supplier_payments_path do %>
              <i class="icon-align-justify"></i>
              <span class="hidden-tablet">Supplier Payments</span>
            <% end %>
          </li>
        <% end %>
        <% if can?(:manage, CustomerPayment) %>
          <li>
            <%= link_to customer_payments_path do %>
              <i class="icon-align-justify"></i>
              <span class="hidden-tablet">Customer Payments</span>
            <% end %>
          </li>
        <% end %>
      <% end %>
      <% if can?(:read, Report) %>
        <li class="nav-header hidden-tablet">Reports</li>
        <li>
          <%= link_to reports_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Reports</span>
          <% end %>
        </li>
        <li>
          <%= link_to rek_accounts_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Rek Accounts</span>
          <% end %>
        </li>
        <li>
          <%= link_to transactions_path do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Transactions</span>
          <% end %>
        </li>
      <% end %>
      <% if can?(:manage, Company) %>
        <li class="nav-header hidden-tablet">Settings</li>
        <li>
          <%= link_to edit_company_path(Company.first) do %>
            <i class="icon-align-justify"></i>
            <span class="hidden-tablet">Company</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_topbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><span>PT. Bandung Bangkit Bersinar</span></a>
      <div class="btn-group pull-right" >
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user"></i><span class="hidden-phone"><%= current_user.full_name %></span>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div class="pull-right">
        <%= link_to user_path(current_user) do %>
          <%= image_tag(img_url, :class => "user-details-avatar", :style=>'width: 35px; height: 35px;') if current_user %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if notice || alert %>
  <div class="alert alert-<%= "#{notice ? 'success' : 'danger'}" %> alert-dismissable", style = "margin-top: 58px;">
    <% if notice %>
      <i class="fa fa-check"></i>
    <% else %>
      <i class="fa fa-ban"></i>
    <% end %>
    <%= link_to "x", "#", class: "close", :"aria-hidden" => true, :"data-dismiss" => "alert" %>
    <strong><%= notice ? notice : alert %></strong>
  </div>
<% end %>
<center>Mohon periksa kurs mata uang dengan mengklik <%= link_to "link", edit_company_path(Company.first) %></center>