config/routes.rb
BandungBangkitBersinar::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => :user_registrations}

  resources :transactions

  resources :mix_items

  resources :users, { path:"user-management" } do
    collection do
      delete :delete_all
    end
    get :export
  end

  resources :suppliers do
    collection do
      delete :delete_all
      get :print_preview
      get :items_info
      get :export
    end
    get :print_orders, :on => :member
  end

  resources :customers do
    collection do
      delete :delete_all
      get :export
      get :items_info
    end
  end

  resources :categories do
    collection do
      delete :delete_all
      get :export
    end
  end

  resources :items do
    collection do
      delete :delete_all
      get :critical
      get :export
    end
  end

  resources :purchase_orders, except: [:edit, :update, :destroy] do
    collection do
      get :supplier_info
      get :items_info
      get :export
    end
    get :print_po, :on => :member
  end

  resources :sales_invoices, except: [:edit, :update, :destroy] do
    collection do
      get :customer_info
      get :items_info
      get :export
    end
    get :print_invoice, :on => :member
  end

  resources :companies, only: [:edit, :update]

  resources :receive_orders, except: [:edit, :update, :destroy] do
    get :export, :on => :collection
    get :print_invoice, :on => :member
  end

  resources :manage_stocks, :except => [:new, :show, :destroy]

  resources :reports, only: [:index, :create] do
    collection do
      get :preview
    end
  end

  resources :supplier_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end

  resources :customer_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end
  resources :rek_accounts, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end


  get "po_history" => "home#purchase_history", :as => "po_history"
  get "sales_history" => "home#sales_history", :as => "sales_history"
  get "file_managers"=>"home#file_managers", :as => "file_managers"
  get "return_po_number/:date" => "purchase_orders#return_number", :as => "return_po_number"
  get "return_so_number/:date" => "sales_invoices#return_number", :as => "return_so_number"
  get "return_receive_number/:date" => "receive_orders#return_number", :as => "return_receive_number"
  get "return_supplier_payment_number/:date" => "supplier_payments#return_number", :as => "return_supplier_payment_number"
  get "return_customer_payment_number/:date" => "customer_payments#return_number", :as => "return_customer_payment_number"
  get "manage_stock/:invoice_number/item/:item_id" => "manage_stocks#new", :as => "manage_item_stock"
  get "reset_data" => "home#reset_data", as: "reset_data"

  root :to => 'home#index'

  match 'elfinder' => 'home#elfinder'
  match '*path', :to => 'pages#routing_error'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  skip_before_filter :verify_authenticity_token, :only => ['elfinder']

  def elfinder
    h, r = ElFinder::Connector.new(
      :root => File.join(Rails.public_path, 'system', 'elfinder'),
      :url => 'http://localhost:3000/system/elfinder',
      :driver => 'LocalFileSystem',
      :perms => {
        'forbidden' => {:read => false, :write => false, :rm => false},
        /README/ => {:write => false},
        /pjkh\.png$/ => {:write => false, :rm => false},
      },
      :extractors => {
        'application/zip' => ['unzip', '-qq', '-o'],
        'application/x-gzip' => ['tar', '-xzf'],
      },
      :archivers => {
        'application/zip' => ['.zip', 'zip', '-qr9'],
        'application/x-gzip' => ['.tgz', 'tar', '-czf'],
      },
      :thumbs => true
    ).run(params)

    headers.merge!(h)
    render (r.empty? ? {:nothing => true} : {:text => r.to_json}), :layout => false
  end

  def index
  	@statistic = Statistic.first
  end

  def purchase_history
  	ordered = PoReceive.history_order
    render json: ordered.map{|o| [o[0].to_i*1000, o[1].to_f]}
  end

  def sales_history
    ordered = SalesInvoice.history_order
    render json: ordered.map{|o| [o[0].to_i*1000, o[1].to_f]}
  end

  def file_managers;end

  def reset_data
    if params[:table_name]
      table_name = params[:table_name]
      ActiveRecord::Base.connection.execute("TRUNCATE #{table_name}") if !["schema_migrations"].include?(table_name)
      case table_name
      when "purchase_orders"
        ActiveRecord::Base.connection.execute("TRUNCATE purchase_order_details") if !["schema_migrations"].include?('purchase_order_details')
      when "sales_invoices"
        ActiveRecord::Base.connection.execute("TRUNCATE sales_invoice_details") if !["schema_migrations"].include?('sales_invoice_details')
      when "suppliers"
        ActiveRecord::Base.connection.execute("TRUNCATE supplier_items") if !["schema_migrations"].include?('supplier_items')
        ActiveRecord::Base.connection.execute("TRUNCATE supplier_item_prices") if !["schema_migrations"].include?('supplier_item_prices')
        ActiveRecord::Base.connection.execute("TRUNCATE supplier_payments") if !["schema_migrations"].include?('supplier_payments')
      when "items"
        ActiveRecord::Base.connection.execute("TRUNCATE manage_stocks") if !["schema_migrations"].include?('manage_stocks')
        ActiveRecord::Base.connection.execute("TRUNCATE mix_items") if !["schema_migrations"].include?('mix_items')
      when "po_receives"
        ActiveRecord::Base.connection.execute("TRUNCATE po_receive_details") if !["schema_migrations"].include?('po_receive_details')
      end
      render json: {data: request.env["HTTP_REFERER"]}
    end
  end
end

app/views/home/file_managers.html.erb
<div id="content" class="span10">
<!-- content starts -->

  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a> <span class="divider">/</span>
      </li>
      <li>
        <a href="#">File Manager</a>
      </li>
    </ul>
  </div>

  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-picture"></i> File Manager</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <div id="elfinder" class="file-manager"></div>
      </div>
    </div><!--/span-->

  </div><!--/row-->


    <!-- content ends -->
</div><!--/#content.span10-->

app/views/home/index.html.erb
<div id="content" class="span10">
  <div class="sortable row-fluid">
    <% if can?(:manage, Item) %>
      <%= link_to critical_items_path, { :class=>"well span3 top-block", :'data-rel'=>"tooltip" } do %>
        <span class="icon32 icon-red icon-inbox"></span>
        <div>Critical Stock</div>
        <div><%= @statistic.total_critical_items %></div>
      <% end %>
    <% end %>

    <% if can?(:manage, PurchaseOrder) %>
      <%= link_to suppliers_path, { :class=>"well span3 top-block", :'data-rel'=>"tooltip" } do %>
        <span class="icon32 icon-red icon-user"></span>
        <div>Jumlah Supplier</div>
        <div><%= @statistic.total_supplier %></div>
      <% end %>
    <% end %>

    <%= link_to purchase_orders_path, { :class=>"well span3 top-block", :'data-rel'=>"tooltip" } do %>
      <span class="icon32 icon-color icon-cart"></span>
      <div>Total Pembelian</div>
      <div><%= number_to_currency(@statistic.total_purchase) %></div>
    <% end %>
    <%= link_to sales_invoices_path, { :class=>"well span3 top-block", :'data-rel'=>"tooltip" } do %>
      <span class="icon32 icon-color icon-cart"></span>
      <div>Total Penjualan</div>
      <div><%= number_to_currency(@statistic.total_sales) %></div>
    <% end %>
  </div>

  <div class="row-fluid sortable">
    <div class="span12">
      <div class="box span6">
        <div class="box-header well" data-original-title>
          <h2><i class="icon-list-alt"></i> Purchase Order Traffic</h2>
          <div class="box-icon">
            <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
          </div>
        </div>
        <div class="box-content">
          <div id="containerPO"></div>
        </div>
      </div><!--/span-->
      <div class="box span6">
        <div class="box-header well" data-original-title>
          <h2><i class="icon-list-alt"></i> Sales Order Traffic</h2>
          <div class="box-icon">
            <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
          </div>
        </div>
        <div class="box-content">
          <div id="containerSO"></div>
        </div>
      </div><!--/span-->
    </div>
  </div>
</div>
<hr>
<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Settings</h3>
  </div>
  <div class="modal-body">
    <p>Here settings can be configured...</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>

<%= javascript_include_tag 'dashboards', :defer => 'defer' %>