config/routes.rb
BandungBangkitBersinar::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => :user_registrations}

  resources :transactions

  resources :mix_items

  resources :users, { path:"user-management" } do
    collection do
      delete :delete_all
    end
    get :export
  end

  resources :suppliers do
    collection do
      delete :delete_all
      get :print_preview
      get :items_info
      get :export
    end
    get :print_orders, :on => :member
  end

  resources :customers do
    collection do
      delete :delete_all
      get :export
      get :items_info
    end
  end

  resources :categories do
    collection do
      delete :delete_all
      get :export
    end
  end

  resources :items do
    collection do
      delete :delete_all
      get :critical
      get :export
    end
  end

  resources :purchase_orders, except: [:edit, :update, :destroy] do
    collection do
      get :supplier_info
      get :items_info
      get :export
    end
    get :print_po, :on => :member
  end

  resources :sales_invoices, except: [:edit, :update, :destroy] do
    collection do
      get :customer_info
      get :items_info
      get :export
    end
    get :print_invoice, :on => :member
  end

  resources :companies, only: [:edit, :update]

  resources :receive_orders, except: [:edit, :update, :destroy] do
    get :export, :on => :collection
    get :print_invoice, :on => :member
  end

  resources :manage_stocks, :except => [:new, :show, :destroy]

  resources :reports, only: [:index, :create] do
    collection do
      get :preview
    end
  end

  resources :supplier_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end

  resources :customer_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end
  resources :rek_accounts, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end


  get "po_history" => "home#purchase_history", :as => "po_history"
  get "sales_history" => "home#sales_history", :as => "sales_history"
  get "file_managers"=>"home#file_managers", :as => "file_managers"
  get "return_po_number/:date" => "purchase_orders#return_number", :as => "return_po_number"
  get "return_so_number/:date" => "sales_invoices#return_number", :as => "return_so_number"
  get "return_receive_number/:date" => "receive_orders#return_number", :as => "return_receive_number"
  get "return_supplier_payment_number/:date" => "supplier_payments#return_number", :as => "return_supplier_payment_number"
  get "return_customer_payment_number/:date" => "customer_payments#return_number", :as => "return_customer_payment_number"
  get "manage_stock/:invoice_number/item/:item_id" => "manage_stocks#new", :as => "manage_item_stock"
  get "reset_data" => "home#reset_data", as: "reset_data"

  root :to => 'home#index'

  match 'elfinder' => 'home#elfinder'
  match '*path', :to => 'pages#routing_error'
end

app/controllers/receive_orders_controller.rb
class ReceiveOrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_po, only: [:new]
  before_filter :find_receive_order, only: [:show, :print_invoice]
  before_filter :list_receive_orders, only: [:index, :export]

  def index;end

  def show
    @receive_order = PoReceive.find_by_id(params[:id])
  end

  def new
    @receive_po = PoReceive.new
    @receive_po.po_receive_details.build
  end

  def create
    @receive_po = current_user.receives_po.build(params[:po_receive])
    if @receive_po.save
      params[:po_receive][:po_receive_details_attributes].each do |po_receive_detail|
        build_supplier_item_prices(params[:po_receive][:transaction_date], params[:po_receive][:supplier_id], po_receive_detail)
        SupplierItem.where(:supplier_id => params[:po_receive][:supplier_id], :item_id => po_receive_detail[1]["item_id"]).update_all(:price => price = po_receive_detail[1]["price"])
      end
      # add debit balance
      SupplierPayment.create!([
        {
          :transaction_date => @receive_po.transaction_date,
          :invoice_number => @receive_po.invoice_number,
          :supplier_id => @receive_po.supplier_id,
          :notes => "PO Receive " + @receive_po.transaction_date.strftime("%d %B %Y"),
          :balance_type => "debit",
          :amount => @receive_po.grand_total_amount,
          :user_id => current_user.id
        }])

      redirect_to receive_orders_path
    else
      render :new
    end
  end

  def return_number
    receive_number = PoReceive.find_next_available_number_for(date: params[:date])
    render json: receive_number.to_json
  end

  def print_invoice
    # respond_to do |format|
    #   format.html do
    #     render :pdf => 'receive_order',
    #      :template => 'previews/receive_orders/show',
    #      :layout => 'transaction.pdf',
    #      :save_only => false
    #   end
    # end
    render 'previews/receive_orders/show', layout: 'print_view'
  end

  def export
    respond_to do |format|
      format.xls
    end
  end

  private
    def find_po
      @po = PurchaseOrder.find_by_id(params[:id])
      @pr_date = Date.today
      @pr_number = PoReceive.find_next_available_number_for
      redirect_to "/404.html" if @po.closed?
    end

    def find_receive_order
      @receive_order = PoReceive.find_by_id(params[:id])
    end

    def list_receive_orders
      @receive_orders = PoReceive.order(:transaction_date)
    end

    def build_supplier_item_prices(date, supplier_id, po_receive_detail_params)
      supplier_item = SupplierItem.where("supplier_id = ? and item_id = ?", supplier_id, po_receive_detail_params[1]["item_id"]).first
      if supplier_item
        supplier_item_id = supplier_item.id
        item_id = supplier_item.item_id
        date_price = date
        price = po_receive_detail_params[1]["price"]

        SupplierItemPrice.create!([
          {
            :supplier_item_id => supplier_item_id,
            :item_id => item_id,
            :date_price => date_price,
            :price => price
          }
        ])
      end
    end
end

app/views/receive_orders/_form.html.erb
<style type="text/css">
  tr.fields td input{width: 150px;}
</style>
<fieldset>
  <div class="row-fluid sortable">
    <div class="box span6">
      <div class="box-content">
        <div class="control-group">
          <%= f.label :po_number, :class => "control-label" %>
          <div class="controls po_number">
            <%= f.text_field :po_number, :class=>"input-xlarge", :placeholder => "invoice number here ..", :readonly => true, :value => purchase_order.po_number %>
            <%= f.hidden_field :currency_type, value: purchase_order.currency_type %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :po_date, "PO Date", :class => "control-label" %>
          <div class="controls po_date">
            <%= f.text_field :po_date, :class=>"input-xlarge", :placeholder => "date here ..", :readonly => true, :value => purchase_order.po_date %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :invoice_number, "Invoice Number", :class => "control-label" %>
          <div class="controls po_number">
            <%= f.text_field :invoice_number, :class=>"input-xlarge", :placeholder => "invoice number here ..", :autofocus => true, :readonly => true, :value => pr_number %>
            <%= f.hidden_field :purchase_order_id, :class=>"input-xlarge", :placeholder => "invoice number here ..", :autofocus => true, :readonly => true, :value => purchase_order.id %>
            <%= f.hidden_field :supplier_id, :class => "sp_info", :value => purchase_order.supplier_id %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :transaction_date, "Date", :class => "control-label" %>
          <div class="controls po_date">
            <%= f.text_field :transaction_date, :class=>"input-xlarge", :placeholder => "date here ..", :value => purchase_order.po_date %>
          </div>
        </div>
      </div>
    </div>
    <div class="box span6">
      <div class="box-content">
        <div class="control-group">
          <%= f.label :name, "Supplier Name", :class => "control-label" %>
          <div class="controls supplier">
            <%= f.text_field :name, :class => "sp_info", :disabled => 'disabled', :value => purchase_order.supplier_full_name %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :address, "Address", :class => "control-label" %>
          <div class="controls">
            <%= f.text_area :address, :rows => 2, :disabled => 'disabled', :class=>"input-xlarge", :placeholder => "supplier address here ..", :value => purchase_order.supplier_address %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :phone, "Phone", :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :phone_number, :disabled => 'disabled', :class=>"input-xlarge", :placeholder => "phone number here ..", :value => purchase_order.supplier_phone_number %>
            </div>
        </div>
        <div class="control-group">
          <%= f.label :contact_person, "Sales Person", :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :contact_person, :disabled => 'disabled', :class=>"input-xlarge", :placeholder => "contact person here ..", :value => purchase_order.supplier_contact_person %>
          </div>
        </div>
      </div>
    </div>
  </div>
</fieldset>

<fieldset>
  <%= render 'po_receive_details', f: f, po: purchase_order %>
</fieldset>

<fieldset>
  <br />
  <div class="row-fluid sortable">
  <!-- <div class="span6"></div> -->
    <!-- <div class="span6">
      <div class="control-group">
        <%#= f.label :kurs, :class => "control-label" %>
        <div class="controls po_number">
          <%#= f.text_field :kurs, :class=>"input-xlarge", :placeholder => "invoice number here ..", :readonly => true, :value => kurs_value %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :total_valas, "Total(Rp)", :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :total_valas, :class=>"input-xlarge valas_total", :placeholder => "invoice number here ..", :readonly => true, :value => usd_to_idr(purchase_order.total_amount) %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :ppn_valas, "PPN(Rp)", :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :ppn_valas, :class=>"input-xlarge valas_ppn", :placeholder => "date here ..", :readonly => true, :value => usd_to_idr(purchase_order.total_ppn) %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :grand_total_valas, "grand total(Rp)", :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :grand_total_valas, :class=>"input-xlarge valas_grand_total", :placeholder => "date here ..", :readonly => true, :value => usd_to_idr(purchase_order.grand_total) %>
        </div>
      </div>
    </div> -->
    <div class="span6">
      <div class="box-content">
        <div class="control-group">
          <%= f.label :kurs, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :kurs, :class=>"input-xlarge", :placeholder => "invoice number here ..", :value => kurs_value, unit: "Rp", :onkeypress=>"return numbersonly(event)", :onkeyup => "kursConvert(this)" %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :total, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :total, :class=>"input-xlarge total_invoice", :placeholder => "invoice number here ..", :readonly => true, :value => purchase_order.total_amount %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :ppn, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :ppn, :class=>"input-xlarge ppn_invoice", :placeholder => "date here ..", :readonly => true, :value => purchase_order.total_ppn %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :grand_total, :class => "control-label" %>
          <div class="controls">
            <%= f.text_field :grand_total, :class=>"input-xlarge grand_total_invoice", :placeholder => "date here ..", :readonly => true, :value => purchase_order.grand_total %>
          </div>
        </div>
      </div>
    </div>
  </div>
</fieldset>

<fieldset>
  <div class="form-actions">
    <%= f.submit 'Save changes', :class => "btn btn-primary" %>
    <button id="cancel-edit" class="btn">Cancel</button>
  </div>
</fieldset>

app/views/receive_orders/_po_receive_details.html.erb
<div class="box span12">
  <div class="box-content">
    <h2>List Items</h2>
    <table id="items-table" class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nama Barang</th>
          <th>Harga(USD)</th>
          <th>Harga(Rp)</th>
          <th>qty</th>
          <th>Subtotal</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% po.purchase_order_details.each do |pd| %>
          <%= f.fields_for :po_receive_details do |f| %>
            <tr class="fields">
              <td><%= pd.item_name %></td>
              <td><%= f.text_field :price, :value => pd.price %></td>
              <td><%= f.text_field :valas, readonly: true, :value => usd_to_idr(pd.price) %></td>
              <td><%= f.text_field :qty, :value => pd.qty, :onkeypress=>"return numbersonly(event)", :onkeyup => "totalTransaction(this)"%></td>
              <td>
                <%= f.text_field :subtotal, readonly: true, :value => pd.subtotal %>
                <%= f.hidden_field :item_id, readonly: true, :value => pd.item_id %>
              </td>
              <td><%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, f) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/receive_orders/_po_receive_details_table.html.erb
<div class="box span12">
  <div class="box-content">
    <h2>List Items</h2>
    <table id="items-table" class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nama Barang</th>
          <th>Harga(USD)</th>
          <th>Harga(Rp)</th>
          <th>qty</th>
          <th>Subtotal</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :po_receive_details do |detail| %>
          <% po.purchase_order_details do |pd| %>
            <tr class="fields">
              <td>
                <%= item.text_field :name, readonly: true, :value => pd.item_name %>
                <%= detail.hidden_field :item_id, readonly: true, :value => pd.item_id %>
              </td>
              <td><%= detail.text_field :price, readonly: true, :value => pd.price %></td>
              <td><%= text_field_tag :price, nil, readonly: true, :value => (pd.price * Company.first.kurs) %></td>
              <td><%= detail.text_field :qty, :value => pd.qty %></td>
              <td><%= detail.text_field :subtotal, readonly: true, :value => pd.subtotal %></td>
              <td><%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, detail) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/receive_orders/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="columnheaders">
      <Font ss:Bold="1" />
    </Style>
  </Styles>  
  <Worksheet ss:Name="Purchase Orders Data">
    <Table>
      <ss:Column ss:Width="20"/>
      <ss:Column ss:Width="100"/>
      <ss:Column ss:Width="160"/>
      <ss:Column ss:Width="80"/>
      <ss:Column ss:Width="80"/>
      <Row>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">No</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">#Osders</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Tanggal</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Supplier</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Total Orders</Data></Cell>
      </Row>
    <% @receive_orders.each_with_index do |receive_order, i| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= i + 1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= receive_order.invoice_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= receive_order.transaction_date.to_formatted_s(:long) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= receive_order.supplier_full_name if receive_order.supplier %></Data></Cell>
        <Cell><Data ss:Type="String"><%= receive_order.total_amount %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/receive_orders/index.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-user"></i> Receive Orders</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
          <thead>
            <tr>
              <td colspan="3"></td>
              <% if current_user.is_admin? %>
                <td class="right">
                  <%= link_to "#", id: 'reset_data', :"data-member" => "po_receives", remote: true do %>
                  <i class="icon-trash"></i> Reset
                  <% end %>
                </td>
              <% end %>
              <td class="right">
                <%= link_to export_receive_orders_path(format: "xls") do %>
                  <i class="icon-folder-open"></i> Export
                <% end %>
              </td>
            </tr>
            <tr>
              <th>#Orders</th>
              <th>Tanggal</th>
              <th>Supplier</th>
              <th>Total Orders</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @receive_orders.each do |receive_order| %>
              <tr>
                <td><%= receive_order.invoice_number %></td>
                <td class="center"><%= receive_order.transaction_date.to_formatted_s(:long) %></td>
                <td class="center"><%= receive_order.supplier_full_name if receive_order.supplier %></td>
                <td class="center"><%= number_to_currency(receive_order.total_amount) %></td>
                <td class="center">
                  <%= link_to receive_order_path(receive_order) do %>
                    <i class="icon-eye-open"></i> View
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>

app/views/receive_orders/new.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-edit"></i> Create Purchase Receive</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_for(@receive_po, :url => receive_orders_path(@receive_po), :html => { :class=>"form-horizontal" }) do |f| %>
          <%= render 'form', f: f, purchase_order: @po, pr_number: @pr_number %>
        <% end %>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>

app/views/receive_orders/show.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-edit"></i> Receive Order Details</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_for("receive order", :html => { :class=>"form-horizontal" }) do |f| %>
          <fieldset>
            <div class="row-fluid sortable">
              <div class="box span6">
                <div class="box-content">
                  <div class="control-group">
                    <%= f.label :invoice_number, :class => "po-label" %>
                    <div class="controls po_number">
                      <%= f.label :invoice_number, @receive_order.invoice_number, :class => "po-label" %>
                    </div>
                  </div>
                  <div class="control-group">
                    <%= f.label :transaction_date, :class => "po-label" %>
                    <div class="controls po_date">
                      <%= f.label :transaction_date, @receive_order.transaction_date.to_formatted_s(:long), :class => "po-label" %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="box span6">
                <div class="box-content">
                  <div class="control-group">
                    <%= f.label :supplier_id, "Supplier Name", :class => "po-label" %>
                    <div class="controls supplier">
                      <%= f.label :supplier_id, @receive_order.supplier_full_name, :class => "po-label" %>
                    </div>
                  </div>
                  <%= f.fields_for :supplier do |f| %>
                    <div class="control-group">
                      <%= f.label :address, "Address", :class => "po-label" %>
                      <div class="controls">
                        <%= f.label :address, @receive_order.supplier_address, :class => "po-label" %>
                      </div>
                    </div>
                    <div class="control-group">
                      <%= f.label :phone, "Phone", :class => "po-label" %>
                        <div class="controls">
                          <%= f.label :phone, @receive_order.supplier_phone_number, :class => "po-label" %>
                        </div>
                    </div>
                    <div class="control-group">
                      <%= f.label :contact_person, "Sales Person", :class => "po-label" %>
                      <div class="controls">
                        <%= f.label :contact_person, @receive_order.supplier_contact_person, :class => "po-label" if @receive_order.supplier_contact_person %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <div class="box span12">
              <div class="box-content">
                <h2>List Items</h2>
                <table id="items-table" class="table table-striped table-bordered responsive">
                  <thead>
                    <tr>
                      <th>No.</th>
                      <th>Nama Barang</th>
                      <th>Harga</th>
                      <!-- <th>Harga(Rp)</th> -->
                      <th>qty</th>
                      <th>Subtotal</th>
                      <!-- <th>Subtotal(Rp)</th> -->
                    </tr>
                  </thead>
                  <tbody>
                    <% @receive_order.po_receive_details.each_with_index do |detail, i| %>
                      <tr>
                        <td><%= i+1 %></td>
                        <td><%= detail.item_name %></td>
                        <td><%= @receive_order.currency_type? ? number_to_currency(detail.price) : number_to_currency(detail.price, unit: "Rp") %></td>
                        <!-- <td><%= number_to_currency(detail.price * @receive_order.kurs, :unit => "Rp") %></td> -->
                        <td><%= number_to_human(detail.qty, units: {unit: "kg"}) %></td>
                        <td><%= @receive_order.currency_type? ? number_to_currency(detail.subtotal) : number_to_currency(detail.subtotal, unit: "Rp")%></td>
                        <!-- <td><%= number_to_currency(detail.subtotal * @receive_order.kurs, :unit => "Rp") %></td> -->
                      </tr>
                    <% end %>
                  </tbody>
                  <tfooter>
                    <!-- <tr>
                      <td colspan="5"><strong>Total</strong></td>
                      <td><%= number_to_currency(@receive_order.total_amount) %></td>
                      <td><%= number_to_currency(@receive_order.total_amount * @receive_order.kurs, :unit => "Rp") %></td>
                    </tr> -->
                    <tr>
                      <td colspan="4"><strong>PPN(10%)</strong></td>
                      <td><%= @receive_order.currency_type? ? number_to_currency(@receive_order.ppn) : number_to_currency(@receive_order.ppn, unit: "Rp")%></td>
                      <!-- <td><%= number_to_currency(@receive_order.ppn * @receive_order.kurs, :unit => "Rp") %></td> -->
                    </tr>
                    <tr>
                      <td colspan="4"><strong>Grand Total</strong></td>
                      <td><%= @receive_order.currency_type? ? number_to_currency(@receive_order.grand_total_amount) : number_to_currency(@receive_order.grand_total_amount, unit: "Rp") %></td>
                      <!-- <td><%= number_to_currency(@receive_order.grand_total_amount * @receive_order.kurs, :unit => "Rp") %></td> -->
                    </tr>
                  </tfooter>
                </table>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <div class="form-actions">
              <%= link_to "Print", print_invoice_receive_order_path(@receive_order), :class => "btn btn-primary", :target => '_blank' %>
              <button id="cancel-edit" class="btn">Cancel</button>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>