config/routes.rb
BandungBangkitBersinar::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => :user_registrations}

  resources :transactions

  resources :mix_items

  resources :users, { path:"user-management" } do
    collection do
      delete :delete_all
    end
    get :export
  end

  resources :suppliers do
    collection do
      delete :delete_all
      get :print_preview
      get :items_info
      get :export
    end
    get :print_orders, :on => :member
  end

  resources :customers do
    collection do
      delete :delete_all
      get :export
      get :items_info
    end
  end

  resources :categories do
    collection do
      delete :delete_all
      get :export
    end
  end

  resources :items do
    collection do
      delete :delete_all
      get :critical
      get :export
    end
  end

  resources :purchase_orders, except: [:edit, :update, :destroy] do
    collection do
      get :supplier_info
      get :items_info
      get :export
    end
    get :print_po, :on => :member
  end

  resources :sales_invoices, except: [:edit, :update, :destroy] do
    collection do
      get :customer_info
      get :items_info
      get :export
    end
    get :print_invoice, :on => :member
  end

  resources :companies, only: [:edit, :update]

  resources :receive_orders, except: [:edit, :update, :destroy] do
    get :export, :on => :collection
    get :print_invoice, :on => :member
  end

  resources :manage_stocks, :except => [:new, :show, :destroy]

  resources :reports, only: [:index, :create] do
    collection do
      get :preview
    end
  end

  resources :supplier_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end

  resources :customer_payments, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end
  resources :rek_accounts, except: [:edit, :update, :destroy] do
    collection do
      get :preview
    end
  end


  get "po_history" => "home#purchase_history", :as => "po_history"
  get "sales_history" => "home#sales_history", :as => "sales_history"
  get "file_managers"=>"home#file_managers", :as => "file_managers"
  get "return_po_number/:date" => "purchase_orders#return_number", :as => "return_po_number"
  get "return_so_number/:date" => "sales_invoices#return_number", :as => "return_so_number"
  get "return_receive_number/:date" => "receive_orders#return_number", :as => "return_receive_number"
  get "return_supplier_payment_number/:date" => "supplier_payments#return_number", :as => "return_supplier_payment_number"
  get "return_customer_payment_number/:date" => "customer_payments#return_number", :as => "return_customer_payment_number"
  get "manage_stock/:invoice_number/item/:item_id" => "manage_stocks#new", :as => "manage_item_stock"
  get "reset_data" => "home#reset_data", as: "reset_data"

  root :to => 'home#index'

  match 'elfinder' => 'home#elfinder'
  match '*path', :to => 'pages#routing_error'
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :code, :name, :unit, :is_active

  has_many :items
  has_many :mix_items

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :unit, presence: true

  def status
    self.is_active ? 'Active' : 'Banned'
  end

  def deactive
    self.update_attributes(:is_active => false)
  end

  def activate
    self.update_attributes(:is_active => true)
  end

  def self.find_next_available_number_for(default=99999)
    self.any? ? (self.maximum(:code, :order => "code") || default).succ : "CT-00001"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  before_filter :find_category, only: [:edit, :update, :destroy]
  before_filter :list_categories, only: [:index, :export]

  def index
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    @category.code = Category.find_next_available_number_for
    @category.save ? (redirect_to categories_path; flash[:notice] = "Category has been created successfully.") : (render :new)
  end

  def export
    respond_to do |format|
      format.xls
    end
  end

  def show;end

  def edit;end

  def update
    params[:activate] ? @category.activate : @category.update_attributes(params[:category])
    @category.save ? (redirect_to categories_path) : (render :edit)
  end

  def destroy
    @category.deactive ? (flash[:notice] = 'Category was successfully banned.') : (flash[:notice] = 'Category was not banned.')
    redirect_to categories_path
  end

  def delete_all
    categories = Category.where("id in (?)", params[:id_all])
    categories.each { |category| category.deactive }
    render :json => categories
  end

  private
    def find_category
      @category = Category.find(params[:id])
    end

    def list_categories
      @categories = Category.order(:name)
    end
end

app/views/categories/_category_items.html.erb
<div class="box span12">
  <div class="box-content">
    <h2>List Items</h2>
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
      <thead>
        <tr>
          <th>Code Items</th>
          <th>CI Number</th>
          <th>Item</th>
          <th>Stock</th>
        </tr>
      </thead>
      <tbody>
        <% category.items.each do |item| %>
          <tr>
            <td><%= item.code %></td>
            <td class="center"><%= item.ci_number %></td>
            <td class="center"><%= item.name %></td>
            <td class="center"><%= number_to_human(item.stock, units: {unit: "kg"}) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div><!--/span-->

app/views/categories/_form.html.erb
<fieldset>
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class=>"input-xlarge", :placeholder => "name here ..", :required => true %>
      <i><%= category.errors[:name].first unless category.errors[:name].blank? %></i>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :unit, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :unit, :class=>"input-xlarge", :placeholder => "unit here ..", :required => true %>
      <i><%= category.errors[:unit].first unless category.errors[:unit].blank? %></i>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Save changes', :class => "btn btn-primary" %>
    <button id="cancel-edit" class="btn">Cancel</button>
  </div>
</fieldset>

app/views/categories/edit.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-edit"></i> Edit Category</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_for(@category, :url => category_path(@category), :method => :put, :html => { :class=>"form-horizontal", :multipart => true }) do |f| %>
          <%= render "form", f:f, category: @category %>
        <% end %>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>

app/views/categories/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="columnheaders">
      <Font ss:Bold="1" />
    </Style>
  </Styles>  
  <Worksheet ss:Name="Purchase Orders Data">
    <Table>
      <ss:Column ss:Width="20"/>
      <ss:Column ss:Width="100"/>
      <ss:Column ss:Width="160"/>
      <ss:Column ss:Width="80"/>
      <ss:Column ss:Width="80"/>
      <Row>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">No</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Code</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Name</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Unit</Data></Cell>
        <Cell ss:StyleID="columnheaders"><Data ss:Type="String">Status</Data></Cell>
      </Row>
    <% @categories.each_with_index do |category, i| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= i + 1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= category.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= category.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= category.unit %></Data></Cell>
        <Cell><Data ss:Type="String"><%= category.status %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/categories/index.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">    
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-user"></i> Category</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <table class="table table-striped table-bordered bootstrap-datatable datatable responsive ">
          <thead>
            <tr>
              <td colspan="5"></td>
              <td class="right">
                <%= link_to new_category_path do %>
                  <i class="icon-plus"></i> 
                  Baru
                <% end %>
                <%= link_to "#", { :id => 'category_delete_all', :'data-remote' => true } do %>
                  <i class="icon-trash"></i> 
                  Hapus
                <% end %>
                <%= link_to export_categories_path(format: "xls") do %>
                  <i class="icon-folder-open"></i> Export
                <% end %>
              </td>
            </tr>
            <tr>
              <th><input type="checkbox" id="check_all"/></th>
              <th>Kode</th>
              <th>Nama</th>
              <th>Satuan</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>   
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= check_box_tag 'myrow_ids[]', category.id, false, :class=>"cls_category_ids" %></td>
                <td><%= category.code %></td>
                <td class="center"><%= category.name %></td>
                <td class="center"><%= category.unit %></td>
                <td class="center"><span class="label <%= status_label(category) %>"><%= category.status %></span></td>
                <td class="center">
                  <%= link_to category_path(category) do %>
                    <i class="icon-eye-open"></i>  
                    Lihat
                  <% end %>
                  <%= link_to edit_category_path(category) do %>
                    <i class="icon-edit"></i>  
                    Edit                                            
                  <% end %>
                  <% if category.is_active %>
                    <%= link_to category_path(category), { :method=>'delete', :'data-confirm'=>'Anda yakin akan menghapus data ini?' } do %>
                      <i class="icon-trash"></i> 
                      Hapus
                    <% end %>
                  <% else %>
                    <%= link_to category_path(category, activate: true), { :class=>"btn btn-warning", :method=>'put', :'data-confirm'=>'Anda yakin akan mengaktifkan user ini?' } do %>
                      <i class="icon-ok"></i>
                      <span class="hidden-tablet">Active</span>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>            
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>

app/views/categories/new.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-edit"></i> Add Category</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <%= form_for(@category, :url => categories_path(@category), :html => { :class=>"form-horizontal", :multipart => true }) do |f| %>
          <%= render 'form', f: f, category: @category %>
        <% end %>
      </div>
    </div><!--/span-->
  </div><!--/row-->
</div>

app/views/categories/show.html.erb
<div id="content" class="span10">
  <!-- content starts -->
  <div class="row-fluid sortable">
    <div class="box span12">
      <div class="box-header well" data-original-title>
        <h2><i class="icon-edit"></i>Category Details</h2>
        <div class="box-icon">
          <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
          <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
          <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
      </div>
      <div class="box-content">
        <div class="box-content">
          <ul class="dashboard-list">
            <li>
              <strong>Code: </strong> <a href="#"><%= @category.code if @category.code %></a><br>
              <strong>Name: </strong> <a href="#"><%= @category.name if @category.name %></a><br>
              <strong>Unit: </strong> <a href="#"><%= @category.unit if @category.unit %></a><br>
            </li>
          </ul>
        </div>
      </div>
    </div><!--/span-->
  </div><!--/row-->
  <div class="row-fluid sortable">
    <%= render 'category_items', category: @category %>
  </div>
</div>